### PR TITLE
Fixed issue vulnerable

### PR DESCRIPTION
**Pull request by abhirup97**
Fixed issue vulnerable

### CODE REVIEW

**Comment by abhirup97** [comment]
test the override issue "yourtheme/woocommerce-catalog-enquiry/woocommerce-catalog-enquiry-variable-product.php"
with the functionality  with variation product and also the pro plugin working with variation product. @Sangi0

**Comment by Sangi0** [comment]
test done

**Comment by abhirup97** [comment]
@Sangi0 please test the flow admin settings and check with pro also

**Comment by Sangi0** [comment]
Test done

**Comment by Sangi0** [comment]
Test done

**Comment by Sangi0** [comment]
Tested

**Pull request merged**
